# -*- coding: utf-8 -*-
"""web development

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C0J_CQvpnVTSVNBMBd6kIcygYmU-SJKF
"""

print("hello world")
print("amiyo is a good boy")
